# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 487b04b25c5bbc46a4582c7dd2e0dd4bf1c51201793e4812aca7b0ad2b3227a505b4e6dfb2b94cdb47a8f085ce8831dd714ba68f0d8a28c88109cc651f342964

test:
  secret_key_base: 991a67b3a76f6f3f9d27cbef27d6711a319ee2ddb2fc0654b556390877ed70353444f7d2a7895911967c21c7d37812a3dd99df0f5c1152b05b7205c94e35a38a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
